apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring
    version: v1
  name: spring-java
  namespace: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
     app: spring
     version: v1
  template:
    metadata:
      labels:
       app: spring
       version: v1
    spec:
      containers:
      - image: 404106681973.dkr.ecr.us-east-2.amazonaws.com/spring:tagvar     

        name: spring
        ports:
        - containerPort: 9090
        resources:
            requests:
                memory: "1Gi"
                cpu: "1"
            limits:
                memory: "1Gi"
                cpu: "1"


---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: springboot
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
#    service.beta.kubernetes.io/aws-load-balancer-internal: "true"

spec:
  ports:
    - port: 9090
      targetPort: 9090
  type: LoadBalancer
  selector:
     app: spring
     version: v1

